# EX02 Solutions
Solutions to the second week's exercises on rigid and perspective transformations.

In these exercises we assume square pixels, so the skew parameter $\beta=0$.

## Exercise 2.1

In [ ]:

f=600; alpha=1; beta=0; cx=cy=400
K=np.array([[alpha*f,beta,cx],[0,f,cy],[0,0,1]])
R=np.eye(3)
t=np.array([0,0.2,1.5])
width,height=2*cx,2*cy
print('resolution =',width,'x',height)
Q=box3d()
proj=projectpoints(K,R,t,Q)
inside=np.all((proj>=0)&(proj< [width,height]),axis=1)
print('all points inside sensor?',inside.all())
P1=np.array([-0.5,-0.5,-0.5])
print('P1 projects to',projectpoints(K,R,t,[P1])[0])


resolution = 800 x 800
all points inside sensor? False
P1 projects to [100. 220.]


## Exercise 2.2

In [ ]:

dist=[-0.2,0,0]
proj_d=projectpoints_dist(K,R,t,Q,dist)
print('P1 with distortion',projectpoints_dist(K,R,t,[P1],dist)[0])
inside=np.all((proj_d>=0)&(proj_d<[width,height]),axis=1)
print('all distorted points inside sensor?',inside.all())


P1 with distortion [120.4  232.24]
all distorted points inside sensor? True


## Exercise 2.3

In [ ]:

width,height=1920,1080
focal=0.455732*width
cx,cy=width/2,height/2
K_gopro=np.array([[focal,0,cx],[0,focal,cy],[0,0,1]])
print('K =')
print(K_gopro)


K =
[[875.00544   0.      960.     ]
 [  0.      875.00544 540.     ]
 [  0.        0.        1.     ]]


## Exercise 2.4

In [ ]:

im=np.tile(np.linspace(0,1,200),(200,1))
K_demo=np.array([[100,0,100],[0,100,100],[0,0,1]])
und=undistortImage(im,K_demo,[-0.2,0,0])
print('undistorted image shape',und.shape)


undistorted image shape (200, 200)


## Exercise 2.5

In [ ]:

H=np.array([[-2,0,1],[1,-2,0],[0,0,3]])
pts=np.array([[1,0,2,2],[1,3,3,4]])
pts_h=np.vstack((pts,np.ones(4)))
qs=H@pts_h
qs=(qs/qs[2])[:2]
print('mapped points:')
print(qs)


mapped points:
[[-0.33333333  0.33333333 -1.         -1.        ]
 [-0.33333333 -2.         -1.33333333 -2.        ]]


## Exercise 2.6

In [ ]:

q2=pts
q1=qs
H_est=hest(q1,q2)
print('estimated H scaled:')
print(H_est/H_est[2,2])


estimated H scaled:
[[-6.66666667e-01 -2.27371531e-16  3.33333333e-01]
 [ 3.33333333e-01 -6.66666667e-01  6.07369995e-16]
 [ 4.30981525e-16  2.49505901e-16  1.00000000e+00]]


## Exercise 2.7

In [ ]:

pts_test=np.random.randn(2,100)
T,pts_norm=normalize2d(pts_test)
print('mean',pts_norm.mean(axis=1))
print('std',pts_norm.std(axis=1))


mean [ 1.77635684e-17 -3.33066907e-18]
std [1. 1.]


## Exercise 2.8

In [ ]:

H_est_n=hest(q1,q2,normalize=True)
print('normalized estimate scaled:')
print(H_est_n/H_est_n[2,2])


normalized estimate scaled:
[[-6.66666667e-01 -3.60091849e-17  3.33333333e-01]
 [ 3.33333333e-01 -6.66666667e-01 -2.01636414e-16]
 [-2.42735683e-16  9.97965660e-17  1.00000000e+00]]


## Exercise 2.9

In [ ]:

q2=np.random.randn(2,100)
q2h=np.vstack((q2,np.ones(100)))
H_true=np.random.randn(3,3)
q1h=H_true@q2h
q1=q1h[:2]/q1h[2]
H_est=hest(q1,q2,normalize=True)
H_true_n=H_true/H_true[2,2]
H_est_n=H_est/H_est[2,2]
print('frobenius error',np.linalg.norm(H_true_n-H_est_n))


frobenius error 2.2419702575676162e-14


## Exercise 2.10

In [ ]:

imA=np.tile(np.linspace(0,1,200),(200,1))
H_true=np.array([[1,0,30],[0,1,20],[0,0,1]])
ptsA=np.array([[50,150,150,50],[50,50,150,150]])
ptsAh=np.vstack((ptsA,np.ones(4)))
ptsBh=H_true@ptsAh
ptsB=ptsBh[:2]/ptsBh[2]
H_est=hest(ptsB,ptsA,normalize=True)
print('H_true:')
print(H_true)
print('H_est scaled:')
print(H_est/H_est[2,2])


H_true:
[[ 1  0 30]
 [ 0  1 20]
 [ 0  0  1]]
H_est scaled:
[[ 1.00000000e+00 -4.63271590e-16  3.00000000e+01]
 [ 5.48852816e-16  1.00000000e+00  2.00000000e+01]
 [ 2.00989635e-18 -3.75899171e-18  1.00000000e+00]]


## Exercise 2.11

In [ ]:

imA_w=warpImage(imA,H_est)
print('warped image shape',imA_w.shape)


warped image shape (200, 200)
